### ISSUE TITLE
User Page

### ISSUE THREAD

**Issue by kyley422** [kyley422/bruin-banos#13]

**Comment by Blek1** [comment]
Userpage has both favorites and reviews displayed

TODO:
Userpage styling
When refreshing the userpage, it removes all the data from the page. Be careful when changing the states as it can create an infinite loop.

**Comment by Blek1** [comment]
Also to note, if the user unfavorites a bathroom on the userpage, it will be removed from the firebase (keeping the bathroom there until the user refreshes/goes back to the userpage)
